name: Generate PDF for Review

on:
  push:
    branches: [ attesa-review ]
  pull_request:
    branches: [ main ]

jobs:
  generate-pdf-for-review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Typst
      uses: typst-community/setup-typst@v3

    - name: Compile Typst document
      run: |
        typst compile main.typ algoritmi-e-complessita.pdf

    - name: Upload PDF as artifact
      uses: actions/upload-artifact@v4
      with:
        name: algoritmi-e-complessita-pdf-review
        path: algoritmi-e-complessita.pdf
        retention-days: 30

    # Attach PDF to PR when pushing to attesa-review
    - name: Find Pull Request
      if: github.ref == 'refs/heads/attesa-review'
      uses: jwalton/gh-find-current-pr@v1
      id: findPR
      with:
        state: open

    - name: Comment PDF on PR
      if: github.ref == 'refs/heads/attesa-review' && steps.findPR.outputs.number
      uses: actions/github-script@v7
      with:
        script: |
          const comment = `📄 **PDF Generated Successfully for Review!**

          The latest PDF has been compiled from this commit and is ready for review.
          You can download it from the [workflow artifacts](${context.payload.repository.html_url}/actions/runs/${context.runId}).

          Commit: ${context.sha.substring(0, 7)}
          Branch: attesa-review`;

          github.rest.issues.createComment({
            issue_number: ${{ steps.findPR.outputs.number }},
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: comment
          });
